name: "build"

on: [push]

jobs:
  vercel: 
    runs-on: ubuntu-latest
    name: "build nextjs app"
    
    steps:
      - uses: actions/checkout@v4

      - name: use node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/

      - name: install dependencies
        run: npm install
      
      - name: run build
        run: npm run build

      - name: run tests
        run: npm test
        env:
          CI: true
          FORCE_COLOR: 1

  call-deployment-workflow:
    needs: vercel
    uses: ./.github/workflows/deploy.yml
