name: choose-os
on:
 workflow_dispatch:
   inputs:
     chosen-os:
       required: true
       type: choice
       options:
       - ubuntu-latest
       - windows-latest
       - macos-latest

jobs:

  test:
    runs-on: ${{ github.event.inputs.chosen-os }}
    steps:
    - run: echo Hello world!
