name: Day of week greeting

on:
  workflow_dispatch
env:
  DAY_OF_WEEK: Tues

jobs:
  weekday_job:
    runs-on: windows-latest
    env:
      FIRST_NAME: Mona
      middle_name: The

    steps:
      - name: "Redefine first name to Adam"
        run: echo "Hello $env:FIRST_NAME"
        env:
          FIRST_NAME: Adam
          Last_Name: Spruce
      - name: "Hello world when it's Monday"
        if: env.DAY_OF_WEEK == 'Mon' 
        run: echo "Hello there $env:FIRST_NAME $env:middle_name $env:Last_Name, today is Monday!"
        env:
          FIRST_NAME: MonaStep
          Last_Name: Octocat
      - name: else
        if: env.DAY_OF_WEEK != 'Mon' 
        run: echo "Hello $env:FIRST_NAME $env:middle_name $env:Last_Name. It's not Monday, it's $env:DAY_OF_WEEK!"

  show-env-vars:
      runs-on: windows-latest
      
      steps:
        - name: "Show env vars"
          run: env
