name: Dump env var values 2

on:
  workflow_dispatch:

jobs:
  dump-env-var-values:
    runs-on: ubuntu-latest
    steps:
      - run: echo 1 - $CI
      - run: echo 2 - no context      
      - run: echo 3 - $GITHUB_ACTION
      - run: echo 4 - ${{ github.action }}    
      - run: echo 5 - $GITHUB_ACTIONS
      - run: echo 6 - ${{ github.actions }}        
      - run: echo 7 - $GITHUB_ACTION_PATH
      - run: echo 8 - ${{ github.action_path }}    
      - run: echo 9 - $GITHUB_ACTOR
      - run: echo 10 - ${{ github.actor }}    
      - run: echo 11 - $GITHUB_API_URL
      - run: echo 12 - ${{ github.api_url }}    
      - run: echo 13 - $GITHUB_BASE_REF
      - run: echo 14 - ${{ github.base_ref }}    
      - run: echo 15a - $GITHUB_EVENT
      - run: echo 16b - ${{ github.event }}    
      - run: echo 15b - $GITHUB_EVENT_NAME
      - run: echo 16b - ${{ github.event_name }}    
      - run: echo 17 - $GITHUB_EVENT_PATH
      - run: echo 18 - ${{ github.event_path }}    
      - run: echo 19 - $GITHUB_GRAPHQL_URL
      - run: echo 20 - ${{ github.graphql_url }}    
      - run: echo 21 - $GITHUB_HEAD_REF
      - run: echo 22 - ${{ github.head_ref }}    
      - run: echo 23 - $GITHUB_JOB
      - run: echo 24 - ${{ github.job }}    
      - run: echo 25 - $GITHUB_REF
      - run: echo 26 - ${{ github.ref }}    
      - run: echo 27 - $GITHUB_REF_NAME
      - run: echo 28 - ${{ github.ref_name }}    
      - run: echo 29 - $GITHUB_REF_PROTECTED
      - run: echo 30 - ${{ github.ref_protected }}    
      - run: echo 31 - $GITHUB_REF_TYPE
      - run: echo 32 - ${{ github.ref_type }}    
      - run: echo 33 - $GITHUB_REPOSITORY
      - run: echo 34 - ${{ github.repository }}    
      - run: echo 35 - $GITHUB_REPOSITORY_OWNER
      - run: echo 36 - ${{ github.repository_owner }}    
      - run: echo 37 - $GITHUB_RUN_ID
      - run: echo 38 - ${{ github.run_id }}    
      - run: echo 39 - $GITHUB_RUN_NUMBER
      - run: echo 40 - ${{ github.run_number }}    
      - run: echo 41 - $GITHUB_SERVER_URL
      - run: echo 42 - ${{ github.server_url }}    
      - run: echo 43 - $GITHUB_SHA
      - run: echo 44 - ${{ github.sha }}    
      - run: echo 45 - $GITHUB_WORKFLOW
      - run: echo 46 - ${{ github.workflow }}    
      - run: echo 47 - $GITHUB_WORKSPACE
      - run: echo 48 - ${{ github.workspace }}    
      - run: echo 49 - $RUNNER_ARCH
      - run: echo 50 - ${{ runner.arch }}    
      - run: echo 51 - $RUNNER_NAME
      - run: echo 52 - ${{ runner.name }}    
      - run: echo 53 - $RUNNER_OS
      - run: echo 54 - ${{ runner.os }}    
      - run: echo 55 - $RUNNER_TEMP
      - run: echo 56 - ${{ runner.temp }}    
      - run: echo 57 - $RUNNER_TOOL_CACHE
      - run: echo 58 - ${{ runner.tool_cache }}    
      
