# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  ifthen-statement:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
      - name: condition 1
        if: "contains($env:GITHUB_ACTOR, 'hubwriter')"
        run: echo Run script for condition 1

      - name: condition 2
        if: ${{ ! contains($env:GITHUB_ACTOR, 'hubwriter') }}
        run: echo Run script for condition 2
