name: Manual workflow

on:
  workflow_dispatch:

jobs:

  ifthen-statement:
    runs-on: ubuntu-latest

    steps:
      - name: condition 1
        if: contains(env.GITHUB_ACTOR, 'hubwriter')
        run: echo Run script for condition 1

