name: Manual workflow

on:
  workflow_dispatch:

jobs:

  ifthen-statement:
    runs-on: ubuntu-latest
    env: 
      GITHUB_REF_NAME: $GITHUB_REF_NAME

    steps:
      - name: print env var
        run: echo The actor is $GITHUB_REF_NAME
      - name: condition 1
        if: contains(env.GITHUB_REF_NAME, 'master') == false
        run: echo The ref is not master, it is $GITHUB_REF_NAME

